version: '3.6'

services:
  bot:
    build: ./Bot
    volumes:
      - ytcmp:/storage:rw
    ports:
      - '3000:3000'
      - '9229:9229'
    environment:
      - 'TGTOKEN='
      - 'ADDRESS='
      - 'CONVADDR=http://convert:1488/api/v1/split'
      - 'LOGDIR='
      - 'DATADIR='
      - 'LENGTHSEC=1800'
    depends_on:
      - 'convert'
  convert:
    build: ./Convert
    container_name: convert
    volumes:
      - ytcmp:/storage:rw
    expose:
      - '1488'
    ports:
      - '7000:7000'
      environment: 
        - 'PORT=1488' 
        - 'LOGDIR='
        - 'DATADIR='
        - 'LENGTHSEC=1800'
volumes:
  ytcmp:
    driver: local
