version: '3.6'

services:
  bot:
    build: ./Bot
    volumes:
      - ytcmp:/storage:rw
    ports:
      - '3000:3000'
      - '9229:9229'
    environment:
      - 'TGTOKEN=1218726205:AAFLJSzFQXuxhQ1c4Wj-mSvguIoPCxpajHk'
      - 'ADDRESS=https://4e566e968a38.ngrok.io'
      - 'CONVADDR=http://convert:1488/api/v1/split'
      - 'LOGDIR=/home/ubuntu/data/LOGS'
      - 'DATADIR=/home/ubuntu/data/DATA'
      - 'LENGTHSEC=1800'
    depends_on:
      - 'convert'
  convert:
    build: ./Convert
    container_name: convert
    volumes:
      - ytcmp:/storage:rw
    expose:
      - '1488'
    ports:
      - '7000:7000'
      environment: 
        - 'PORT=1488' 
        - 'LOGDIR=/home/ubuntu/data/LOGS'
        - 'DATADIR=/home/ubuntu/data/DATA'
        - 'LENGTHSEC=1800'
volumes:
  ytcmp:
    driver: local
